### PR TITLE
Mali driver integration compeleted [FIXED]

### PR DESCRIPTION
**Pull request by ngoquang2708**
Change-Id: Ic3e50724a2c95d361b6113159d9d362dd0073e19

### CODE REVIEW

**Comment by diepquynh** [comment]
Does it working now?

**Comment by ngoquang2708** [comment]
loaded into ui. then crash. likely the cause is ril class. sleep for 15min. check it out later

**Comment by ngoquang2708** [comment]
yes,it is.
please cleanup your local git or delete it and reclone your repo. add missing stubs... i ll very appreciate abou that

**Comment by diepquynh** [comment]
Yeah, i'll do that. All the whole time i use Sammy's stock kernel source to build CM11 :D

**Comment by diepquynh** [comment]
AOSP repo sync is done. Now i'll gonna do sth with it

**Pull request merged**
